### ISSUE TITLE
Implement 3D models

### ISSUE THREAD

**Issue by DaveEmmerson** [DaveEmmerson/SpaceWar2#11]
For a few reasons
 It will look nicer
 The graphics can be modelled in Blender or similar
 Anything more than the simple circles used at the moment would be difficult by hand

How?
Not sure at the moment.
Each GameObject needs a way of drawing itself. It could just have a Draw, but then it's going to need to be passed the world/view/projection transforms to apply to its effects. Or it could be passed a default effect that is already set up and extract them from there? 
Possibly a better method is to expose an XNA Model and have the engine loop over each GameObject, getting the Model and looping over using the standard Model drawing code.
How do we handle different effects for different game objects? Will there need to be?
This is the confusing bit!

I might just get it done so at least something works, and then worry about more later...

**Comment by DaveEmmerson** [comment]
This is linked to particles...

**Comment by DaveEmmerson** [comment]
Ok. I did this a while ago!

The arrows are still drawn manually. So I'll leave this open until I've sorted that out.

**Comment by mattwatson** [comment]
Could close it and raise a more specific issue?

**Comment by DaveEmmerson** [comment]
Done
