### ISSUE TITLE
Start organising classes into namespaces and folders to structure project

### ISSUE THREAD

**Issue by mattwatson** [DaveEmmerson/SpaceWar2#14]

**Comment by DaveEmmerson** [comment]
Yeah... there are quite a few classes in the go like.

gameobjects namespace with the interface, class, and implementations?

Not sure what else off the top of my head

**Comment by mattwatson** [comment]
Yep, sounds good. Can you think of a better name than GameObjects? I mean
thats what they are but seems a bit redundant...

**Comment by mattwatson** [comment]
P.s. I'm happy to do the moving as resharper does most of the work.

**Comment by DaveEmmerson** [comment]
Game?
Objects? :)

Hmm...

I'm not sure what they are really, other than that.

I noticed you'd done a couple already. Redownloaded master try again
on this Model malarky. I might have to draw myself a little map of how
things are now, on actual paper, to try to work out what to do.
