### ISSUE TITLE
If GameObject.ApplyForce() is not called in a game loop, forces are not reset.

### ISSUE THREAD

**Issue by mattwatson** [DaveEmmerson/SpaceWar2#15]
Not sure how to fix it without forcing them to be reset at the end of every game loop. Was trying to get away without needing to do that

**Comment by DaveEmmerson** [comment]
I can't see a way around it.

Either we need to clear the forces at the start of GameObject update, and make sure nothing adds forces earlier. Or make resolve forces only retrievable once and reset on retrieving.

I like reset on retrieving. You can always copy into another var if it needs to be used more than once during the update?

**Comment by mattwatson** [comment]
I've got an idea on this. Will have a bash later

**Comment by DaveEmmerson** [comment]
Good stuff.

I'm on lunch and then work for another hour and a half, then sleep, then maybe get half an hour to code before the evening routine starts!
