### ISSUE TITLE
Check instantaneous update of velocity

### ISSUE THREAD

**Issue by DaveEmmerson** [DaveEmmerson/SpaceWar2#16]
I think we are updating the velocity from the current acceleration after updating it. If we are then that's not quite right. We need to average the previous time's acceleration and the new one.

**Comment by DaveEmmerson** [comment]
I mean position, not velocity. And velocity for the second one... lol. 

Velocity = Velocity + Acceleration \* dT
Position = Position + Velocity \* dT
Assumes constant velocity over dT

OldVelocity = Velocity
Velocity = Velocity + Acceleration \* dT
Position = Position + (Old Velocity + New Velocity) / 2

Or use 1/2 A dT^2, but seems less legible.

I've no idea what impact this would have! Perhaps make the gravity feel more correct?

**Comment by mattwatson** [comment]
Yes you are right. We are snapshotting physical measurements at random
points (unless game loop is being called at exactly the same intervals),
and using instantaneous values in the calcs. It should be done properly.

Sounds like something we could have unit tests for.

**Comment by DaveEmmerson** [comment]
I'll start some tests if I can. Seems sensible. Preservation of energy might be a good start?

Pretty tired from yesterday!

Not really got far with anything today.
