### ISSUE TITLE
Should the vector + operator be adding displacement?

### ISSUE THREAD

**Issue by DaveEmmerson** [DaveEmmerson/SpaceWar2#22]
Two forces offset by 1,0 with vector 0,1 should result in one vector with disp 1,0 and vector 2,0?

Unit test possibility here...?

I might try to add one. At least if I set the project up it's good work and we can amend the test if you disagree ;)

**Comment by mattwatson** [comment]
Yes I agree with this case, but less sure what it should do when the
displacements are different.

Put it in a file called Force_spec or Force_test and we can put all the
unit tests for the Force class in there

**Comment by DaveEmmerson** [comment]
Ok. I was going to have a project called SpaceWarTests

Then have like ForceTests.cs, GameObjectTests.cs,  etc

Perhaps mirror the namespaces underneath too? I've
not used sepArate ns in a unit tested thing before,

**Comment by mattwatson** [comment]
Sounds fine. Cool

**Comment by DaveEmmerson** [comment]
Ok... here's the crack, I think.
- operator on Force (as we have it at least) only makes sense if the displacement is the same.

Good example for me is one sphere of r=2 and one cube of s=3
Apply one unit upward force at 1,0 and another at 2,0
The resultant force will be different for each object, but the force + operator does't know about the objects

Really, the object itself has to deal with multiple forces?

**Comment by mattwatson** [comment]
I fixed (avoided?) this by getting rid of the + operator. It was only used
once and for something that doesn't care about displacement. Replaced it
with AddVector() method
