### ISSUE TITLE
Choose and Introduce mocking framework

### ISSUE THREAD

**Issue by mattwatson** [DaveEmmerson/SpaceWar2#23]
Some contenders
Moq
RhinoMocks
NSubstitute

**Comment by DaveEmmerson** [comment]
I know of mocking and what it is... but have never quite got it.

Will look at those though.

I'm at the end of my marathon dish washing session and did a full day
of work today. Have another full day and am intending to go
into Durham... so I think it's bed for me as soon as I'm done.

Will check these out tomorrow and might ask at work what they use
if anything.

**Comment by DaveEmmerson** [comment]
I like how NSub looks in your example one.

**Comment by DaveEmmerson** [comment]
I've used it now and I like it.
