### ISSUE TITLE
Updated forces system

### ISSUE THREAD

**Issue by DaveEmmerson** [DaveEmmerson/SpaceWar2#7]
To allow gravity to continue working, but to make other forces easier to add.

As I'm writing this, it's occurring to me that the ship's thrusters could be added
using this. I think you said the collision system could be part of too? :)

**Comment by mattwatson** [comment]
Yeah good idea. Would be nice to treat every force completely generically, and just sum them up and calculate the resultant force each frame. Might not be as easy as it sounds :P

**Comment by DaveEmmerson** [comment]
wrt your todos, I originally did have all gameobjects having mass and acceleration when everything had gravity...

Then when I removed the sun being affected by the ships, I moved it out into a separate interface
for causers and causees (I just made that word up).

I vote move both into gameobject. Now that you have separated sources and participants through the
simulator itself, there's no need for the separate interfaces I don't think. Although it does mean adding
in a mass for the ships. Part of removing that in the first place was bcause I couldn't be arsed to include
it in the calc and it was easier to assume it was 1 :D Not really a problem to do though.

**Comment by mattwatson** [comment]
This is done. Now we have ApplyForce() and ResolveForce() on the GameObject. Currently ResolveForce() also wipes all the forces out, but I might change that to an explit ResetForce() method because we might want to query it several times

**Comment by DaveEmmerson** [comment]
Awesome. I shall have a look tomorrow :)
