### ISSUE TITLE
Ship model loads, but does not draw (or draws out of camera view)

### ISSUE THREAD

**Issue by DaveEmmerson** [DaveEmmerson/SpaceWar2#9]
I may have seen it in the far distance, or it is very small! Or it's just not displaying at all
and what I've seen is some sort of artefact.

**Comment by DaveEmmerson** [comment]
Daft sod.

The model in Blender was too small! :D

Scaled it up and it's visible now.

Might have done something else too, because that seems a bit easy... dunno.

Got the models hacked in for the ships for a test anyway.

**Comment by mattwatson** [comment]
Cool have you pushed changes up to github? I'm excited to see this!

I did a couple of small changes. Now made a branch so I can try to prise
apart the graphics stuff from the physics stuff before it gets too hairy.
I've checked in my branch so you can take a look as it progresses

Matt

**Comment by DaveEmmerson** [comment]
I've got a branch going called Models. Very work in progress.

I have a Camera class, which is a work in progress too.

**Comment by mattwatson** [comment]
Quite interested to see... Would u mind uploading the branch? If you try to
'git push origin' it will tell you that you don't have origin set up and
suggest the command line that you need to set it up...

I'm liking the sound of it :) been trying to understand the current
implementation (xna stuff). What actually is an effect?

Matt

**Comment by DaveEmmerson** [comment]
Already should be there :) at least it seemed to have worked

To get yours I did git checkout -b name origin/name

The xna stuff is pretty basic and probably not even the right way of doing it ;)

Effect is the xna class for representing shaders. I have a very simple one going that is in the .fx file in the content project.

You write your hlsl which is almost like C. Then you tell XNA to load it with the content pipeline. It gives you an Effect object which can be passed parameters , have its techniques/passes called.

Mine

**Comment by DaveEmmerson** [comment]
Mine has one technique that has one pass.

In that one pass it has a vertex shader and a pixel shader, compiled from a couple of functions.

There's a lot of bumf at the top, some variables which are global and therefore parameters the xna can write to. Some struct defs for passing in and out data from the shaders. Then the functions themselves. The functions do very little bar take in the vertices and throw them back out with the colour that was set on them already. Interpolated with a parameter colour.

I hope to get the texture stuff that's started actually working. I also want the suns to be light sources, so need to figure out a nice way of doing that.

In the long run, the shaders can do calculations and modern cards can even have 'geometry' shaders which can actually create vertices, not just amend input ones. That would be neat!

I know nothing much about them yet... just learning, so not much to pass on

**Comment by mattwatson** [comment]
Cool yeah much clearer what's going on now.

Suns as light sources! how cool is that =)

I got the branch but haven't tried running it yet.

**Comment by mattwatson** [comment]
Ah I think you need to add the Camera.cs to git, commit it, and push to
origin... it's missing from the Model's branch

Matt

**Comment by DaveEmmerson** [comment]
That's weird. I was petty sure I'd pushed up to date. Nevermind
